version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/bin/
      - terraform --version
      - echo "Terraform installed."
      - echo "Listing current directory structure:"
      - ls -R

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd data-delivery-pipeline/terraform  # Adjust this path as needed
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform plan -out=tfplan
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - terraform/*.tf
