version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform..."
      - rm -f /usr/bin/terraform
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/bin/
      - terraform --version
      - echo "Terraform installed."

  pre_build:
    commands:
      - echo "Verifying directory structure..."
      - pwd  # Print current directory
      - ls -al  # List files to understand the structure
      - echo "Navigating to the terraform directory..."
      - cd terraform || (echo "Terraform directory not found!" && exit 1)
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform plan -out=tfplan
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - terraform/*.tf
